# Graph building configuration
input_dir: /vols/cms/liv/cmsgnn/data/ntuple_PU200_numEvent1000/
#input_dir = /eos/cms/store/group/ml/GNNTrackingHackathon/data
output_dir: ../output/PU200/1.5GeV/

selection:
    pt_min: 1.5 # GeV
    phi_slope_max: 0.06
    z0_max: 27.5
    eta_range: [-5, 5]

