# Graph building configuration
input_dir: /home/lhv14/validationNtuple/ntuple_PU200/new_simids/ 
output_dir: /home/lhv14/cmsgnn/output/
selection:
    pt_min: 2 # GeV
    phi_slope_max: 0.006
    z0_max: 100
    n_phi_sections: 1
    n_eta_sections: 1
    eta_range: [-5, 5]
    endcaps: true
    phi_reflect: false
    remove_intersecting_edges: true
    

